version: '3'

services:
  backend:
    build: backend
    image: server
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
    depends_on:
      - db
      - redis
    volumes:
      - ./:/code:ro
      - ./model:/model:ro
      - ./video:/video:ro
    environment:
      - DATABASE_URL=postgresql://postgres:bread@db:5432/bread
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8543:8543"
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8543"]
    container_name: backend


  counter:
      image: server
#      deploy:
#        resources:
#          reservations:
#            devices:
#              - driver: nvidia
#                count: 1
#                capabilities: [ gpu ]

      depends_on:
        - db
      volumes:
        - ./:/code:ro
        - ./model:/model:ro
        - ./video:/video:ro
      environment:
        - DATABASE_URL=postgresql://postgres:bread@db:5432/bread
        - NVIDIA_VISIBLE_DEVICES=all
      ports:
        - "8544:8544"
      container_name: counter

      command: ["uvicorn", "counter.main:app", "--host", "0.0.0.0", "--port", "8544"]

  frontend:
    build: frontend
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
    ports:
      - "9033:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - ./model:/model:ro
      - ./video:/video:ro
    restart: always
    container_name: frontend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - NVIDIA_VISIBLE_DEVICES=all


  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bread
      - POSTGRES_DB=bread

  worker1:
    image: server
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
    command: celery -A autolabel.worker.celery worker --loglevel=info --hostname=worker1@%h -Q queue1
    volumes:
      - ./backend:/usr/src/app
      - ./model:/model:ro
#      - /root/.cache:/root/.cache:ro
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
      - backend
      - redis



  redis:
    image: redis:7

  dashboard:
    image: server
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
      - worker1

volumes:
  postgres_data: