version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: "sqlite:latest"
    volumes:
      - ./counting_system.db:/app/counting_system.db
